baseURL = 'https://centralizedlogging.io/'
languageCode = 'en-us'
title = 'centralizedlogging.io'
theme = 'hugo-book'

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content.en'
  weight = 1

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/alex-shpak/hugo-book"
  weight = 10

[[menu.after]]
  name = "Hugo Themes"
  url = "https://themes.gohugo.io/hugo-book/"
  weight = 20

[params]
  BookTheme = 'Auto'
